name: my-postgres
director_uuid: XXXXXX

releases:
  - {name: my-postgres, version: latest}
stemcells:
  - alias: bosh-google-kvm-ubuntu-trusty-go_agent
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: postgresql_server_node
    instances: 1
    azs: [us-central1-a]
    jobs:
    - name: my_pg_server
      release: my-postgres
    vm_type: xlarge.disk
    cloud_properties:
      tags:
      - allow-ssh
    stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
    persistent_disk_type: '307200'
    networks:
      - name: services-1

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

